before:
  hooks:
    - go vet ./...
    - go test -v ./...
builds:
  -
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    image_templates:
    - quay.io/mittwald/kubernetes-secret-generator
    extra_files:
    - util/copy_secret.go
    - main.go
    - go.mod
    - go.sum