apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: secret-generator-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: secret-generator
          image: mittwald/kubernetes-secret-generator:latest